// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: application.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addApplication = `-- name: AddApplication :exec

INSERT INTO "application" (
    id,
    tenant_id,
    name,
    description,
    created_at,
    updated_at
) VALUES (
    $1, -- id
    $2, -- tenant_id
    $3, -- name
    $4, -- description
    $5, -- created_at
    $6 -- updated_at
)
`

type AddApplicationParams struct {
	ID          uuid.UUID        `db:"id"`
	TenantID    uuid.UUID        `db:"tenant_id"`
	Name        string           `db:"name"`
	Description *string          `db:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   *time.Time       `db:"updated_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddApplication(ctx context.Context, arg AddApplicationParams) error {
	_, err := q.db.Exec(ctx, addApplication,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM "application" WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one

SELECT
    id,
    tenant_id,
    name,
    description,
    created_at,
    updated_at
FROM "application"
WHERE
    id = $1
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsFromTenant = `-- name: ListApplicationsFromTenant :many
SELECT
    id,
    tenant_id,
    name,
    description,
    created_at,
    updated_at
FROM "application"
WHERE
    tenant_id = $1
`

func (q *Queries) ListApplicationsFromTenant(ctx context.Context, tenantID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsFromTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE "application" SET
    tenant_id = $1,
    name = $2,
    description = $3,
    updated_at = $4
WHERE id = $5
`

type UpdateApplicationParams struct {
	TenantID    uuid.UUID  `db:"tenant_id"`
	Name        string     `db:"name"`
	Description *string    `db:"description"`
	UpdatedAt   *time.Time `db:"updated_at"`
	ID          uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
