// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_mfa_code.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEmailMfaCode = `-- name: AddEmailMfaCode :exec
INSERT INTO
    email_mfa_code (
        id,
        user_id,
        email,
        token,
        created_at,
        expires_at,
        is_used
    )
VALUES
    (
        $1,
        -- id
        $2,
        -- user_id
        $3,
        -- email
        $4,
        -- token
        $5,
        -- created_at
        $6,
        -- expires_at
        $7 -- is_used
    )
`

type AddEmailMfaCodeParams struct {
	ID        uuid.UUID        `db:"id"`
	UserID    uuid.UUID        `db:"user_id"`
	Email     string           `db:"email"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
	IsUsed    bool             `db:"is_used"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddEmailMfaCode(ctx context.Context, arg AddEmailMfaCodeParams) error {
	_, err := q.db.Exec(ctx, addEmailMfaCode,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsUsed,
	)
	return err
}

const deleteEmailMfaCode = `-- name: DeleteEmailMfaCode :exec
DELETE FROM
    email_mfa_code
WHERE
    id = $1
`

func (q *Queries) DeleteEmailMfaCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailMfaCode, id)
	return err
}

const getEmailMfaCodeByToken = `-- name: GetEmailMfaCodeByToken :one
SELECT
    id,
    user_id,
    email,
    token,
    created_at,
    expires_at,
    is_used
FROM
    email_mfa_code
WHERE
    user_id = $1
    AND token = $2
`

type GetEmailMfaCodeByTokenParams struct {
	UserID uuid.UUID `db:"user_id"`
	Token  string    `db:"token"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetEmailMfaCodeByToken(ctx context.Context, arg GetEmailMfaCodeByTokenParams) (EmailMfaCode, error) {
	row := q.db.QueryRow(ctx, getEmailMfaCodeByToken, arg.UserID, arg.Token)
	var i EmailMfaCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const revokeEmailMfaCodeByUserID = `-- name: RevokeEmailMfaCodeByUserID :exec
DELETE FROM
    email_mfa_code
WHERE
    user_id = $1
`

func (q *Queries) RevokeEmailMfaCodeByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeEmailMfaCodeByUserID, userID)
	return err
}

const updateEmailMfaCode = `-- name: UpdateEmailMfaCode :exec
UPDATE
    email_mfa_code
SET
    user_id = $1,
    email = $2,
    token = $3,
    created_at = $4,
    expires_at = $5,
    is_used = $6
WHERE
    id = $7
`

type UpdateEmailMfaCodeParams struct {
	UserID    uuid.UUID        `db:"user_id"`
	Email     string           `db:"email"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
	IsUsed    bool             `db:"is_used"`
	ID        uuid.UUID        `db:"id"`
}

func (q *Queries) UpdateEmailMfaCode(ctx context.Context, arg UpdateEmailMfaCodeParams) error {
	_, err := q.db.Exec(ctx, updateEmailMfaCode,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsUsed,
		arg.ID,
	)
	return err
}
