version: "2"

sql:
  - engine: "postgresql"
    queries: "./commands"
    schema: "./migrations"
    gen:
      go:
        out: "./sqlc"
        package: "pgstore"
        emit_db_tags: true
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "pg_catalog.varchar"
            nullable: true
            go_type:
              type: "*string"
          - db_type: "text"
            nullable: true
            go_type:
              type: "*string"
          - db_type: "pg_catalog.timestamp"
            nullable: true
            go_type:
              type: "*time.Time"
