services:
  postgres:
    image: postgres:alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_LOGGING: "on"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-logs:/var/log/postgresql
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory='/var/log/postgresql'
      -c log_filename='postgresql.log'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
